name: Syntax Test

on: [push, pull_request]

env:
  PACKAGE: INI Syntax

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: (New-Object Net.WebClient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1", "github.ps1")
      - run: |
          ./github.ps1 "bootstrap" -verbose
          ./github.ps1 "run_syntax_tests" -verbose

  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh run_syntax_tests
